### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Milmoor** [martin-doyle/node-red-contrib-aedes#25]
Not sure if it's an issue of node-red-contrib-aedes, or Aedes itself. I recently switched from node-red-contrib-mqtt-broker on my Raspberry Pi (thanks). I get a (node:2156) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 statusUpdate listeners added. Use emitter.setMaxListeners() to increase limit. I don't get this error when I uninstall node-red-contrib-aedes. I did some googling, found this https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners but I'm out of my league here.
Everything does seem to function as it should, but error should not occur :).

**Comment by martin-doyle** [comment]
This is propably within Node-Red. Is node:2156 the node-red-contrib-aedes node? Could you provide the flow and the log, please? I would like to reproduce the error in my environment. A memory leak would be a serious issue.
By the way, for stress testing I use the mqtt-benchmark tool (see https://github.com/moscajs/aedes#mosca-vs-aedes).

**Comment by martin-doyle** [comment]
Some more questions: Is this happening after redeploying the flows several times or do you have multiple MQTT nodes?

**Comment by Milmoor** [comment]
I've not been able to find how to translate the number to a specific node. The error isn't there when I deinstall node-red-contrib-aedes, and it's in the terminal console output just before node-red-contrib-aedesline. So I assume it's node-red-contrib-aedes. I get this error at startup of Node-Red, in the terminal console. I will provide the exact output later on.

My flow is too large for proper debugging. I'm currently cloning my setup so I can do some testing and trimming. I will either report an other node is the culprit, or provide an example later on.

I have but one MQTT broker node, but do have several nodes which communicate with it. This happens every time I restart Node-Red (node-red-stop, node-red-start). I'm not sure if it happens while running as well. I'll check.

**Comment by martin-doyle** [comment]
How many MQTT in and out nodes, how many external MQTT clients do you use? What does the status of the node-red-contrib-aedes say? I would like to setup a similar flow

**Comment by Milmoor** [comment]
I'll do an export of my flow, including a summary. It's currently cloning, so can't check right now.

**Comment by Milmoor** [comment]
It's not node-red-contrib-aedes, at least not on it's own. I'm not sure what is causing the issue. When I start deleting parts of flows, the issue disappears after some surgery. But I fail to find the logic. So it's not a specific node or flow. Maybe the entire flow is just getting to big to handle? I'll start splitting things up. That was on the agenda anyway. I'll report back if I do find something on node-red-contrib-aedes, but for now it is victim of circumstance.

Thanks for looking into this and for the package. It's really easy to use.

**Comment by martin-doyle** [comment]
Thanks for the clarification. 
This is actually a NodeJS warning as you mentioned in your first comment, not a Node-Red warning. So, **_node:2156_** is not a Node-Red node. NodeJS has a warning limit of 10 listeners on the same event in order to help preventing memory leaks. 
If it is a one time message when deploying your flows you probably have more then 10 nodes having the same listener. You can reduce the number of nodes or just ignore the message.
If it occurs later when running Node-Red you probably face a memory leak issue in one of your nodes. This is dangerous and might lead to a crash of your system.

**Comment by Milmoor** [comment]
Thanks, that helps. Still learning a lot.
I'll check again later on, but for now does seem to only occur at startup. If I ignore it, at least one listener won't get its statusUpdate. Does not seem good thing to have with a listener. I'm not running a lot of software on the Raspberry Pi and certainly nothing exotic, so the culprit probably is a module in node-red, now to find out which one. Hopefully splitting the flow in multiple parts will create different events the listeners want to subscribe to.
