### ISSUE TITLE
explementation please

### ISSUE THREAD

**Issue by Maximus1** [martin-doyle/node-red-contrib-aedes#3]
can you please tell me what it does? is it an alternative to mosquitto?

**Comment by martin-doyle** [comment]
Yes. There are several implementations of an MQTT broker. See also a [List of MQTT brolers](https://github.com/mqtt/mqtt.github.io/wiki/brokers)

[Aedes](https://github.com/moscajs/aedes) is one of them implemented in JavaScript. 
[node-red-contrib-aedes](https://github.com/martin-doyle/node-red-contrib-aedes) makes Aedes easily available in Node-Red. You do not need to install an external broker. Just use this node.

**Comment by Maximus1** [comment]
thanks for your quick reply. :-)
