### ISSUE TITLE
Connect Aedes mqtt from device to IBM (Node-Red)

### ISSUE THREAD

**Issue by maityneil001** [martin-doyle/node-red-contrib-aedes#30]
Hello, @martin-doyle I have installed node-red in IBM cloud using the catalog node-red app. There I installed this module as well. Now how can I connect my device to node-red so I can send data to node-red via mqtt.

I am presently using mqtt box and could not connect to node-red mqtt broker. I used the app URL as mqtt broker URL. is that right? Please let me know if you would like to know more info.

**Comment by martin-doyle** [comment]
Sorry, I do not have any experience with the IBM cloud. The only topic I found is [Node red and mqtt on ibm cloud (bluemix)?](https://discourse.nodered.org/t/node-red-and-mqtt-on-ibm-cloud-bluemix/3023/23).

**Comment by martin-doyle** [comment]
Could you provide the flow or your node settings, please?

**Comment by martin-doyle** [comment]
@maityneil001 Any news on this issue? Even if you found a solution it would be useful for other users.

**Comment by maityneil001** [comment]
@martin-doyle well honestly I did not get any resolution, which is why I shifted to AWS as I do have some knowledge on AWS.

**Comment by martin-doyle** [comment]
@maityneil001 Can we close the issue?

**Comment by maityneil001** [comment]
@martin-doyle oh yes sure. I think this should be a closed issue.
