### ISSUE TITLE
0.3.6 Cannot read property 'emit' of undefined, using node-red 1.1.3 Docker

### ISSUE THREAD

**Issue by scottpage** [martin-doyle/node-red-contrib-aedes#31]
node-red 1.1.3 Docker image
node-red-contrib-aedes 0.3.6
Fresh flows.json, no other nodes, and default Flow 1 tab.
Also, no other nodes are installed aside from those that ship with node-red 1.1.3.

node-red crashes, with the following error log:
[Error gist](https://gist.github.com/scottpage/e37de1cd9ffeee2373f2fe010cce272a)

Tried with and without mongodb connection string.

I haven't found anything with the same error using aedes-persistence-mongodb as a search.

**Comment by scottpage** [comment]
Woke up this morning, node-red was running, and I was unable to reproduce this error.
As a precaution, I pulled the latest node-red image (still 1.1.3) and recreated the container.

Closing as this must have been caused by state of my local machine at the time.

**Comment by scottpage** [comment]
Disregard my previous comment.
It crashes when the MongoDB connection string field is not empty.

**Comment by martin-doyle** [comment]
Could you provide the flow and/or your node settings, please?

**Comment by scottpage** [comment]
[Example flow](https://gist.github.com/scottpage/492d005da28804b4cc57045a200b6228)
[Settings - Using defaults](https://gist.github.com/scottpage/2b7aed41c54681d78fe8caabcbc638e2)

In the example flow, the mongodb connection string is empty.
If I add it, the node-red Docker container crashes continuously.

**Comment by martin-doyle** [comment]
Looks like it is an issue with the newest Node-RED Version 1.1.
Let me check this and I will get back to you.

**Comment by martin-doyle** [comment]
OK. This has nothing to do with the new Node-RED version. I get the same error message if I set the MongoDB string AND the MongoDB is not available at the entered host and port.

I got 
`12 Aug 21:11:24 - TypeError: Cannot read property 'emit' of undefined`
when my MongoDB was offline.

**Comment by martin-doyle** [comment]
Just to make it clear. You need to have a running MongoDB. It is not part of this node.

**Comment by martin-doyle** [comment]
@scottpage Is this topic still open or can we close the issue?
