### ISSUE TITLE
Made with Aedes

### ISSUE THREAD

**Issue by robertsLando** [martin-doyle/node-red-contrib-aedes#4]
Hi, I'm a maintainer of aedes mqtt broker, we are creating a section on aedes __Made with Aedes__ where we will add some interesting projects that are using Aedes. Are you interested on this? Can we add this project to the list?

**Comment by martin-doyle** [comment]
Yes. Sure. I would appreciate it.

**Comment by robertsLando** [comment]
:+1:

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/pull/440
