### ISSUE TITLE
Raspberry Pi not showing Aedes node

### ISSUE THREAD

**Issue by adamelli** [martin-doyle/node-red-contrib-aedes#43]
When searched on Node-Red Palette, no aedes or "node-red-contrib-aedes" shows up. I tried downloading it via the command prompt of my Raspberry Pi Zero:

```
pi@raspberrypi:~ $ npm install node-red-contrib-aedes
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ node-red-contrib-aedes@0.5.0
updated 1 package and audited 129 packages in 40.469s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Anything obvious that should be done?

`npm init package.json` and `npm init /home/pi/package.json` result in errors.

**Comment by adamelli** [comment]
Before that I ran `bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)`

I'm not sure how else I should download nodejs 14.16.0 LTS.

**Comment by martin-doyle** [comment]
What are the nodejs and Node-RED versions you use? I you want  to install a node from the command line make sure you are in the correct folder $HOME/.node-red.

Could you post the results of node -v, npm -v and node-red -v, please?

**Comment by adamelli** [comment]
pi@raspberrypi:~ $ node -v
v12.20.1
pi@raspberrypi:~ $ node-red -v
5 Mar 13:27:11 - [info] 

Welcome to Node-RED
===================

5 Mar 13:27:11 - [info] Node-RED version: v1.2.9
5 Mar 13:27:11 - [info] Node.js  version: v12.20.1
5 Mar 13:27:11 - [info] Linux 5.10.11+ arm LE

**Comment by martin-doyle** [comment]
I am not sure why the node does not show up in your Palette. Are you able to install other nodes?
Did you try to install the node in the folder $HOME/.node-red instead of $HOME?

**Comment by adamelli** [comment]
Yes, I can install other nodes. 

I did not try that. Instead I just used Mosquitto broker.

**Comment by martin-doyle** [comment]
OK. Sorry to hear that. Can we close the issue?
