### ISSUE TITLE
Node-red update 1.3.5, new error when loading aedes 

### ISSUE THREAD

**Issue by Aaron0621** [martin-doyle/node-red-contrib-aedes#49]
Hi there!
 
I have a problem after updating node-red to 1.3.5.

I get a missing node type error regarding "aedes broker":

"Flows stopped due to missing node types."

the commandline shows this error

Waiting for missing types to be registered:
5 Jul 09:31:42 - [info]  - aedes broker

 node-red-contrib-aedes:aedes broker : Error: Could not locate the bindings file. Tried:
→ /home/pi/.node-red/node_modules/snappy/build/binding.node
 → /home/pi/.node-red/node_modules/snappy/build/Debug/binding.node
 → /home/pi/.node-red/node_modules/snappy/build/Release/binding.node
 → /home/pi/.node-red/node_modules/snappy/out/Debug/binding.node
 → /home/pi/.node-red/node_modules/snappy/Debug/binding.node
 → /home/pi/.node-red/node_modules/snappy/out/Release/binding.node
 → /home/pi/.node-red/node_modules/snappy/Release/binding.node
 → /home/pi/.node-red/node_modules/snappy/build/default/binding.node
 → /home/pi/.node-red/node_modules/snappy/compiled/12.18.0/linux/arm/binding.node

Could you tell me what am I doing wrong?

Thank you

**Comment by Aaron0621** [comment]
Sorry, I looked over that the node's name changed, thats why it gave the error message.

All resolved :)

**Comment by Chris2B91** [comment]
Good morning.
I have got exactly the same issue, but I am unable to see how to fix it.

How did you get it fixed ?

Thanks

14 Nov 08:05:23 - [warn] [node-red-contrib-aedes/aedes-mqtt-broker] Error: Could not locate the bindings file. Tried:
 → /home/pi/node_modules/snappy/build/binding.node
 → /home/pi/node_modules/snappy/build/Debug/binding.node
 → /home/pi/node_modules/snappy/build/Release/binding.node
 → /home/pi/node_modules/snappy/out/Debug/binding.node
 → /home/pi/node_modules/snappy/Debug/binding.node
 → /home/pi/node_modules/snappy/out/Release/binding.node
 → /home/pi/node_modules/snappy/Release/binding.node
 → /home/pi/node_modules/snappy/build/default/binding.node
 → /home/pi/node_modules/snappy/compiled/16.13.0/linux/arm/binding.node
