### ISSUE TITLE
ERR_DLOPEN_FAILED when installing on 2.1.4

### ISSUE THREAD

**Issue by nileio** [martin-doyle/node-red-contrib-aedes#56]
While installing the node on version 2.1.4, the following console error appear
 ```
[node-red-contrib-aedes/aedes-mqtt-broker] Error: Module did not self-register: '~/.node-red/node_modules/snappy/build/Release/binding.node'.
```
When going to manage pallette to check the status of the node, it has a warning sign next to it , with the following message
`ERR_DLOPEN_FAILED`

Any thoughts ?
Thank you and thanks for sharing the node

**Comment by martin-doyle** [comment]
Could you please try the latest Node-RED version 2.2.2?

**Comment by martin-doyle** [comment]
Does the issue still exist?

**Comment by nileio** [comment]
sorry i kept this issue open - will create a new issue if this still exists. thanks
