### ISSUE TITLE
Broker publish something repeatedly on its own

### ISSUE THREAD

**Issue by semesta31** [martin-doyle/node-red-contrib-aedes#64]
MQTT Aedes Broker publish topic "$SYS/af98066f-eb5b-4ec7-8ece-e2cf67bd154c/heartbeat" on its own
I don't have that topic, even after I give security  username and password, it still publish that topic every minutes

**Comment by martin-doyle** [comment]
This is by design see https://github.com/moscajs/aedes/issues/244.

**Comment by semesta31** [comment]
Thankss!
