### ISSUE TITLE
Cannot find module '/data/home/nodered/.node-red/node_modules/mongodb/index.js'

### ISSUE THREAD

**Issue by HGlab01** [martin-doyle/node-red-contrib-aedes#80]
After installation I see the warning in the paket manager

Error: Cannot find module '/data/home/nodered/.node-red/node_modules/mongodb/index.js'. Please verify that the package.json has a valid "main" entry (line:19)

![image](https://github.com/user-attachments/assets/3bfb02e2-0d5e-41a0-875f-d72424529cfa)

And the node is not available
I just want to use the in-memory approach

**Comment by martin-doyle** [comment]
Could you provide some more information about your environment, please? Operating system, NodeJS version, Node-RED version.

**Comment by HGlab01** [comment]
sure, sorry for the short issue description!

HW: Raspberry Pi 3 Modell B +
OS: Victron Energy v3.40 (Debian based, special OS to run a Victron Controller https://github.com/victronenergy/venus)
NodeJS: 18.20.3

Welcome to Node-RED
===================
29 Jul 17:42:17 - [info] Node-RED version: v3.1.10
29 Jul 17:42:17 - [info] Node.js  version: v18.20.3
29 Jul 17:42:17 - [info] Linux 5.10.110-rpi-venus-4 arm LE

Hope this helps

**Comment by HGlab01** [comment]
I have no idea why, but today as, I installed it again (for the log) it worked ant the node is available and the server is running.

Thanks for your quick reply and support!
